### ISSUE TITLE
Not closing all connections.

### ISSUE THREAD

**Issue by Somebi** [nodejs/node-v0.x-archive#25494] opened 2015-06-09 14:05 UTC
Using:
Ubuntu
node.js stable v0.12.4

I have noticed, that node is not closing all connections at once.
It's closing some part of connections. Usually about 50-70% of them and the rest are closed after few mins or so. Sometimes it doesn't close them at all.

Closed/Ended connections counter doesn't match with opened counter. Missing about 30%~ of end/close/error events.

Last test show me that there are about 20957 ESTABLISHED connections left via netstat, but clients already closed for about 20 mins or so.
Clients netstat show only few connections established (around 5-20~).
Only after killing server, all connections were closed.

Whether something wrong inside node core or i'm missing some Ubuntu configurations.
Test was made from 4 different machines to a single server.

Test case:

```javascript
// Client
var net=require('net');
var sockets=10000;


for(var i=0;i<sockets;i++){
	net.connect({
		host:'51.211.21.7',
		port:8888
	});
}

console.log('Launched');

// Server
var net=require('net');

var opened=0, closed=0, ended=0, error=0;
var server = net.createServer(function(c) { //'connection' listener
	opened++;

	c.on('close', function() {
		closed++;
	});
	c.on('end', function() {
		ended++;
	});
	c.on('error',function(){
		error++;
	});
});
server.listen(8888, function() { //'listening' listener
  console.log('server bound');
});

setInterval(function(){
	console.log('Opened',opened,'Closed:',closed,'Ended:',ended,'Error:',error);
},1000);

console.log('Launched');

```

**Comment by brendanashworth** [comment] 2015-06-09 16:52
cross-ref: https://github.com/nodejs/io.js/issues/1924

**Comment by Somebi** [comment] 2015-06-10 08:39
Any news?

**Comment by dnakamura** [comment] 2015-06-10 20:14
Managed to reproduce, looking into the root of the issue.
PS for those on windows you need to adjust your dynamic port range (despite what microsoft says, mine only allowed ~3-4k by default)

**Comment by Somebi** [comment] 2015-06-15 12:53
dnakamura have you found anything?

**Comment by dnakamura** [comment] 2015-06-15 19:15
I think I've tracked it down. On shutdown node doesnt actually close its sockets/file handles, it relies on the OS to perform the cleanup.
When I run the sample, the client ends by crashing (a timeout error in the connection routine, presumably because the server has reached the max number of connections). This causes ```abort()``` to be called, rather than ```exit()```.  From the [posix docs](http://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_05), ```abort()``` does not need to properly close all the open handles. 
>If the main() function returns to its original caller, or if the exit() function is called, all open files are closed (hence all output streams are flushed) before program termination. Other paths to program termination, such as calling abort(), need not close all files properly

The solution is for the the server to close stale connections. (BTW, this situation could also occur if the endpoints lose connectivity). Look into using ```socket.setKeepAlive()```, and ```socket.setTimeout()``` for closing inactive sockets. I reran a modified version of the sample, and the problem looks to be avoided.

**Comment by Somebi** [comment] 2015-06-15 21:02
Hmmm thank you. Will have some clues now do dig into tomorrow at work.

**Comment by brendanashworth** [comment] 2015-09-29 06:10
I'm going to close this in favor of continuing discussion at https://github.com/nodejs/node/issues/1924, as it is more updated. Thanks!

**Closed by brendanashworth** 2015-09-29 06:10 UTC
