### ISSUE TITLE
url.parse and url.format is non-inversible for urls with invalid characters in hostnames.

### ISSUE THREAD

**Issue by lxe** [nodejs/node-v0.x-archive#8636] opened 2014-10-28 01:15 UTC
```
> url.parse('http://host.com%20probably_a_path_or_a_part_of_host/foo/bar')
{ protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'host.com',
  port: null,
  hostname: 'host.com',
  hash: null,
  search: null,
  query: null,
  pathname: '%20probably_a_path_or_a_part_of_host/foo/bar',
  path: '%20probably_a_path_or_a_part_of_host/foo/bar',
  href: 'http://host.com/%20probably_a_path_or_a_part_of_host/foo/bar' }
> url.format({ protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'host.com',
  port: null,
  hostname: 'host.com',
  hash: null,
  search: null,
  query: null,
  pathname: '%20probably_a_path_or_a_part_of_host/foo/bar',
  path: '%20probably_a_path_or_a_part_of_host/foo/bar',
  href: 'http://host.com/%20probably_a_path_or_a_part_of_host/foo/bar' })
'http://host.com/%20probably_a_path_or_a_part_of_host/foo/bar'
```

Looks like url.parse assumes that everything after and including the first character that is invalid to appear in hostnames is a path. 

Then, in url.format (which creates the `href` attribute in url.parse as well) places a slash between the host and the path.

This is making tests fail.

**Comment by jasnell** [comment] 2015-06-03 23:17
Could this be a duplicate of #8520?

**Comment by jasnell** [comment] 2015-06-03 23:18
See: https://github.com/nodejs/node/issues/49

**Closed** 2023-04-22 17:04 UTC
Labels: url
