### ISSUE TITLE
Segfault node v0.11.14 related to TLS

### ISSUE THREAD

**Issue by matejkramny** [nodejs/node-v0.x-archive#8780] opened 2014-11-25 20:22 UTC
Running https://github.com/CastawayLabs/dproxy.js.. Occasionally, it quits with segmentation fault..

It is caught using `segfault-handler`.

Stack trace:

```
PID 20 received SIGSEGV for address: 0x11
/srv/app/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x1185)[0x7fc0d1619185]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340)[0x7fc0d1dfe340]
/usr/local/bin/node(uv_write+0x1c)[0xb8a84c]
/usr/local/bin/node(_ZN4node12TLSCallbacks6EncOutEv+0x23a)[0xb621ea]
/usr/local/bin/node(_ZN4node12TLSCallbacks21OnClientHelloParseEndEPv+0x30)[0xb64340]
/usr/local/bin/node(_ZN4node6crypto7SSLWrapINS_12TLSCallbacksEE9EndParserERKN2v820FunctionCallbackInfoINS4_5ValueEEE+0x5d)[0xb49b1d]
/usr/local/bin/node(_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+0x92)[0x781002]
/usr/local/bin/node[0x79e5f8]
[0x1fb117c0634e]
```

If i'm reading this correctly, a client isn't sending proper TLS request and causes an internal node failure.

I'm determined to find the root cause of this. If this is genuinely not my fault (dproxy project), then other projects using TLS and SNI may be endangered.

Happened for v0.11.13 and v.0.11.14

/cc @tjfontaine as it seems related to TLS

**Comment by indutny** [comment] 2015-05-14 10:46
May I ask you to give a try to https://github.com/iojs/io.js/pull/1702 ?

**Comment by matejkramny** [comment] 2015-05-14 13:17
Ok will do.

Thanks @indutny!

**Comment by jasnell** [comment] 2015-06-04 05:46
@matejkramny ... any updates on this? 
@indutny ... was this fixed in io.js?

**Comment by migounette** [comment] 2015-06-04 20:13
@indutny @misterdjules @jasnell @matejkramny 
Guys, the problem found on my side is (and was) not easy to reproduce. My environment in which I have this depends on multiple servers in order to get loads on a node with a WebRTC application.

At this stage, I don't have any valid core dump due to a stupid problem of ulimit on our testing system (fixed now), but so far so good, I can't see this issue since we moved to 0.12
I didn't get the time to revert the node to a previous version.

So, I can help for investigating this issue if we can succeed to have a light test case.

**Comment by indutny** [comment] 2015-06-06 22:40
@migounette what do you think about https://github.com/nodejs/io.js/pull/1910 ?

**Closed** 2023-04-22 17:03 UTC
Labels: tls
