### ISSUE TITLE
Not handling leap seconds correctly?

### ISSUE THREAD

**Issue by yushih** [nodejs/node-v0.x-archive#25871] opened 2015-08-18 06:14 UTC
On my Linux system, when I use Glibc's localtime(3) to convert epoch to time, leap seconds are taken into account. But it seems that node.js's Date function doesn't do this. Here's the example in the shell:
```
$ TZ=right/UTC node -e 'console.log(new Date(1341100824*1000))'
Sun Jul 01 2012 00:00:24 GMT+0000 (UTC)
```
The result doesn't agree with others:
```
$  TZ=right/UTC perl -le 'print scalar localtime $ARGV[0]' 1341100824
Sat Jun 30 23:59:60 2012

$ TZ=right/UTC date -d @1341100824
Sat Jun 30 23:59:60 UTC 2012
```

As you can see when I calculate the time span between 2012 and 1970 the result can be 24 seconds off, which is pretty significant for some applications.

**Comment by trevnorris** [comment] 2015-08-18 09:49
That's a V8 thing. Node doesn't control the Date implementation. We'd probably want to file an issue with the V8 team.

/cc @ofrobots This an issue you'd ever find problematic in practice?

**Comment by ofrobots** [comment] 2015-08-18 15:37
It is actually the EcmaScript standard the ignores leap seconds: http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.1. This is working as intended as per the language spec.

**Comment by brendanashworth** [comment] 2015-09-29 07:37
closing as a non-issue

**Closed by brendanashworth** 2015-09-29 07:37 UTC
