### ISSUE TITLE
Error when configuring on arm7

### ISSUE THREAD

**Issue by ghost** [nodejs/node-v0.x-archive#7622] opened 2014-05-14 07:21 UTC
Steps to reproduce on Debian 7:

```
git clone https://github.com/joyent/node.git
cd node
git checkout v0.7.8
./configure --openssl-libpath=/usr/lib/ssl


{ 'target_defaults': { 'cflags': [],
'default_configuration': 'Release',
'defines': [],
'include_dirs': [],
'libraries': []},
'variables': { 'host_arch': 'arm',
'node_install_npm': 'true',
'node_install_waf': 'true',
'node_prefix': '',
'node_shared_v8': 'false',
'node_shared_zlib': 'false',
'node_use_dtrace': 'false',
'node_use_openssl': 'true',
'node_use_system_openssl': 'false',
'strict_aliasing': 'true',
'target_arch': 'arm',
'v8_use_snapshot': 'true'}}
creating ./config.gypi
creating ./config.mk
Traceback (most recent call last):
File "tools/gyp_node", line 58, in
run_gyp(gyp_args)
File "tools/gyp_node", line 18, in run_gyp
rc = gyp.main(args)
File "./tools/gyp/pylib/gyp/init.py", line 471, in main
options.circular_check)
File "./tools/gyp/pylib/gyp/init.py", line 111, in Load
depth, generator_input_info, check, circular_check)
File "./tools/gyp/pylib/gyp/input.py", line 2289, in Load
depth, check)
File "./tools/gyp/pylib/gyp/input.py", line 433, in LoadTargetBuildFile
includes, depth, check)
File "./tools/gyp/pylib/gyp/input.py", line 387, in LoadTargetBuildFile
build_file_path)
File "./tools/gyp/pylib/gyp/input.py", line 984, in ProcessVariablesAndConditionsInDict
ProcessConditionsInDict(the_dict, is_late, variables, build_file)
File "./tools/gyp/pylib/gyp/input.py", line 861, in ProcessConditionsInDict
variables, build_file)
File "./tools/gyp/pylib/gyp/input.py", line 1010, in ProcessVariablesAndConditionsInDict
build_file)
File "./tools/gyp/pylib/gyp/input.py", line 1025, in ProcessVariablesAndConditionsInList
ProcessVariablesAndConditionsInDict(item, is_late, variables, build_file)
File "./tools/gyp/pylib/gyp/input.py", line 1010, in ProcessVariablesAndConditionsInDict
build_file)
File "./tools/gyp/pylib/gyp/input.py", line 1025, in ProcessVariablesAndConditionsInList
ProcessVariablesAndConditionsInDict(item, is_late, variables, build_file)
File "./tools/gyp/pylib/gyp/input.py", line 984, in ProcessVariablesAndConditionsInDict
ProcessConditionsInDict(the_dict, is_late, variables, build_file)
File "./tools/gyp/pylib/gyp/input.py", line 861, in ProcessConditionsInDict
variables, build_file)
File "./tools/gyp/pylib/gyp/input.py", line 984, in ProcessVariablesAndConditionsInDict
ProcessConditionsInDict(the_dict, is_late, variables, build_file)
File "./tools/gyp/pylib/gyp/input.py", line 842, in ProcessConditionsInDict
if eval(ast_code, {'builtins': None}, variables):
File "", line 1, in
NameError: name 'armv7' is not defined while evaluating condition 'armv7==1' in /tmp/node/deps/v8/tools/gyp/v8.gyp while loading dependencies of /tmp/node/node.gyp\
while trying to load /tmp/node/node.gyp
```

**Comment by jasnell** [comment] 2015-06-03 17:59
Is this a duplicate of #7222 ?

**Comment by fivdi** [comment] 2015-06-03 18:23
@jasnell no, it's a different issue. The issue described here happened when `./configure --openssl-libpath=/usr/lib/ssl` was called before building, #7222 was at runtime on ARMv6 machines.

**Closed** 2023-04-22 16:59 UTC
Labels: defer-to-converged
