### ISSUE TITLE
Access violation in nodejs when restarting a listening server

### ISSUE THREAD

**Issue by Arno-v** [nodejs/node-v0.x-archive#25365] opened 2015-05-22 07:50 UTC
Nodejs version 0.12.3
Windows 7 and Windows 2012 x64

For our application we need a https or spdy server which can be restarted using a path on the filesystem. On the first call to open() this functions OK, however on the second call it often crashes nodejs. The crash occurs in

https://github.com/joyent/node/blob/master/src/stream_wrap.cc

on line 492. The variable wrap = NULL.

We have tried this with https as well as with spdy.
Code:

``` javascript
function RestartableHttps() {
    var server = null;
    var sockets = [];
    var closing = false;
    var setServer=function(options,hostName) {
        server = spdy.createServer(options, app);
        server.on('connection', function (socket) {
            if (closing) {
                socket.destroy();
                return;
            }
            sockets.push(socket);
            socket.once('close', function () {
                console.log('socket closed');
                sockets.splice(sockets.indexOf(socket), 1);
            });
        });
        closing = false;
        server.listen(443,hostName,function() {
            console.log("Listening on 443");
        });
    }

    var createCertOptions = function (path, type) {
        var keyPath = path + '/Settings/' + type + '.key';
        var certPath = path + '/Settings/' + type + '.crt';
        var caCert = 'Webserver/ca.crt';
        if (!fs.existsSync(keyPath))
            return null;
        if (!fs.existsSync(certPath))
            return null;
        if (!fs.existsSync(caCert))
            return null;
        var options = {
            key: fs.readFileSync(keyPath),
            cert: fs.readFileSync(certPath),
            ca: [fs.readFileSync(caCert)]
        };
        return options;
    }

    var forcedClose = function (cb) {
        if (server === null) {
            cb();
            return;
        }
        closing = true;
        for (var i = 0; i < sockets.length; i++) {
            sockets[i].destroy();
        }
        sockets = [];
        server.close(cb);
    }


    this.open = function (path, certificateType,hostName) {
        var open = function () {
            var options = createCertOptions(path, certificateType);
            if (options === null)
                server = null;
            else
                setServer(options,hostName);
        }
        forcedClose(open);
    }    
}
```

**Comment by jasnell** [comment] 2015-05-26 20:45
@Arno-v ... thanks for the code but it's not clear from the code exactly how to recreate the behavior you're seeing. Can you provide a more complete snippet?

**Comment by KenanSulayman** [comment] 2015-05-26 23:59
Here's an actually readable and usable version of the code:

```
var fs = require("fs");
var spdy = require("spdy");

var restartableHttps = function () {
    var server = null;
    var sockets = [];
    var closing = false;
    
    var setServer = function(options,hostName) {
        server = spdy.createServer(options, function (a, b) {
            b.end("Hello world");
        });

        server.on('connection', function (socket) {
            if (closing) {
                socket.destroy();
                return;
            }
            sockets.push(socket);
            socket.once('close', function () {
                console.log('socket closed');
                sockets.splice(sockets.indexOf(socket), 1);
            });
        });
        closing = false;
        server.listen(443,hostName,function() {
            console.log("Listening on 443");
        });
    }

    var createCertOptions = function (path) {
        var keyPath = path + 'key';
        var certPath = path + 'cert';
        var caCert = 'ca';

        if (!fs.existsSync(keyPath))
            return -1;
        
        if (!fs.existsSync(certPath))
            return -2;
        
        if (!fs.existsSync(caCert))
            return -3;
        
        var options = {
            key: fs.readFileSync(keyPath),
            cert: fs.readFileSync(certPath),
            ca: [fs.readFileSync(caCert)]
        };
        
        return options;
    }

    var forcedClose = function (cb) {
        if (server === null) {
            cb();
            return;
        }
        closing = true;
        for (var i = 0; i < sockets.length; i++) {
            sockets[i].destroy();
        }
        sockets = [];
        server.close(cb);
    }

    this.open = function (path, hostName) {
        var open = function () {
            var options = createCertOptions(path);
            if (options === null || options < 0) {
                server = null;

                console.warn(options);
            } else {
                setServer(options,hostName);
            }
        }

        forcedClose(open);
    }    
};

var x = new restartableHttps()

x.open("./", "127.0.0.1");
x.open("./", "0.0.0.0");
```

@Arno-v could you please clarify if you're talking about an error in the means of: "Error: listen EADDRINUSE 0.0.0.0:443", or "Segmentation Fault"?

Thanks

**Comment by Arno-v** [comment] 2015-05-27 08:44
@KenanSulayman 
I am talking about an access violation in Windows which happens if you try to dereference a NULL pointer in C++. It is probably the same as a segmentation fault in UNIX/Linux.

it happens in:

https://github.com/joyent/node/blob/master/src/stream_wrap.cc

on line 492. The variable wrap = NULL.

I modified the code in stream_wrap.cc to so it would test for wrap==NULL, and this would prevent node from crashing, however, the server would not start listening again.

The restartableHttps  object is used in a much larger program. It is used because we want to be able to switch to a different configuration  in runtime. We want to close the listening server, and restart it with different certificates. The command to switch comes from another connection on localhost.

We use a pattern in which we keep track of the connections, and destroy the connections via socket.destroy if we want to switch the configuration.

I have created a sample program and directories which exhibit the behaviour. where can I upload this zip-file?

**Comment by EricSmekens** [comment] 2015-05-27 09:28
https://github.com/EricSmekens/testNodeJS

Here is the sample project. Certificates probably need to updated for your machine name.

**Comment by dnakamura** [comment] 2015-05-27 20:10
To be clear, to reproduce, run program and visit http://localhost/SwitchServer
If so, its working fine for me

**Comment by EricSmekens** [comment] 2015-05-27 20:48
Addition: To reproduce it, open a link to test.html and then on a second tab/browser, navigate to SwitchServer.
Try again a few times, it does seem to happen randomly.
________________________________
Van: dnakamura<mailto:notifications@github.com>
Verzonden: ‎27-‎5-‎2015 22:13
Aan: joyent/node<mailto:node@noreply.github.com>
CC: Eric Smekens<mailto:ericsmekens@msn.com>
Onderwerp: Re: [node] Access violation in nodejs when restarting a listening server (#25365)

To be clear, to reproduce, run program and visit http://localhost/SwitchServer
If so, its working fine for me

---

**Comment by EricSmekens** [comment] 2015-05-28 16:40
Issue also reproduceable on Windows 8.1 - Node v0.12.4. Node silently terminates.

**Comment by Arno-v** [comment] 2015-06-01 13:06
I finally found the problems. It is part the application, and part node.js not handling a strange situation properly.
By entering these lines in line 413 stream_wrap.cc, node no longer crashes, but generates a javascript exception:
````c++
  StreamWrap* wrap = Unwrap<StreamWrap>(args.Holder());
  if (wrap == NULL)
  {
	  args.GetReturnValue().Set(EIO);
	  return;
  }
````
This way I found out that a the js application tried to send a response over a destroyed socket, res is being send AFTER the server has been restarted:
````JavaScript
var counter=0;
app.get('/TestPoll',function(req,res){
  counter++;
  setTimeout(function(){
      res.send({counter:counter})
      },500);
});
````
When I look at the rest of the stream_wrap.cc source, it seems to me that the line
````c++
  StreamWrap* wrap = Unwrap<StreamWrap>(args.Holder());
````
Could initialize wrap to NULL on more places.

**Comment by dnakamura** [comment] 2015-06-01 20:25
I have also been looking at the problem, and I am able to reproduce on Windows and Linux. It does look like the issue is caused by writing to a socket that has been destroyed. Ideally, I/O operations on sockets should be checking to see if they have been destroyed.  At the moment I'm working on a simplified test case to reproduce the issue

**Comment by dnakamura** [comment] 2015-06-03 19:49
I think I have this tracked down and it has to do with the way file io is processed by the thread pool.  Basically, when the write to the socket occurs, it is still open (and thus the checks all pass). A request is then put in the queue to be processed by a worker in the thread pool. Before the request gets picked up, the socket gets closed, thus when the threadpool worker starts the request it segfaults.  Ideally, ```destroy() ``` should set the state to closed (to prevent further read/writes), and wait for outstanding requests to finish before actually closing the handle and settig it to null. Now its just a matter of figuring out how to make that happen

**Comment by dnakamura** [comment] 2015-06-05 19:59
This aught to fix the issue  eed93923ab

**Comment by dnakamura** [comment] 2015-06-23 18:33
I was looking at this some more and my previous conclusion was wrong. In  the end the problem is that you are closing the underlying socket and the server tries to write to the TLS socket (which shares a handle, but is not notified when the regular socket is destroyed). 
The solution is to listen for the ```secureConnection``` event rather than the ```connection``` event

**Comment by jasnell** [comment] 2015-06-25 20:45
@dnakamura ... given your most recent comment, is the fix in https://github.com/joyent/node/commit/eed93923ab75f582fcd0bbc35694e4ccbf80aded still necessary?

**Comment by Arno-v** [comment] 2015-06-26 05:54
The problem remains that nodejs crashes and does not throw an exception in
the original code. I think the fix is still necessary.

**Comment by EricSmekens** [comment] 2015-06-26 06:32
I think so as well, at this moment nodejs silently terminates.

**Comment by dnakamura** [comment] 2015-06-26 15:44
@jasnell Strinctly speaking no, eed9392  is not required. However, it is still probably useful to keep so that any future bugs will fail gracefully rather than segfault.

@EricSmekens  The ideal solution would be to modify the tls socket code to detect when you have closed the underlying handle. However you do bring up another interesting point, why does node silently terminate rather than printing out the standard segfault info?

**Comment by EricSmekens** [comment] 2015-06-26 18:45
@dnakamura For me, (Node 0.12.5), it is not printing any error/info when it crashes.

If I am using 'secureConnection' instead of 'connection', then I will receive an error and it seems that it occurs fewer times. (EADDRINUSE).

**Comment by jasnell** [comment] 2015-06-26 19:05
@EricSmekens ... just to cover all the bases, can you check to see if the same issue occurs in the latest io.js?

**Comment by dnakamura** [comment] 2015-07-02 18:50
@EricSmekens sounds like  you are getting that error because you are trying to bind to the server socket before it has been released. Looking at my code I added a delay, so maybe I was hitting the same problem. Relevant code:
``` 
 var forcedClose = function (cb) {
        if (server === null) {
            cb();
            return;
        }
        var delayedCb = function(){setTimeout(cb, 1000));
        closing = true;
        server.close(delayedCb);
        for (var i = 0; i < sockets.length; i++) {
            sockets[i].destroy();
        }
        sockets = [];
    }
```
Also note, I moved ```server.close()``` before the for loop. This stops the server from accepting new connections while you are closing the old ones.

**Comment by dnakamura** [comment] 2015-07-02 18:57
Also, for anybody thats interested, the problem arises because while the TLS socket, and the normal socket share the file handle, they maintain little no level of coordination. My initial solution was to add a line to the TLSSocket constructor ``` socket.once('close', function(){self.detroy();});```, however this does not work due to some of the oddities of the handle, namely the ```close()``` method of the underlying handle which has code equivalent to the following:
```
function close(cb){
  //do stuff
  this.close = cb;
  cb();
}
```
Which means that a second call to ```close()```  on  the same file handle does not behave as expected

**Closed** 2023-04-22 17:01 UTC
Labels: streams, net
