### ISSUE TITLE
net.js throws error ECONNRESET if an older socket is closed before the latest one.

### ISSUE THREAD

**Issue by 09silverware** [nodejs/node-v0.x-archive#9331] opened 2015-03-05 01:02 UTC
The following server will throw an ECONNRESET error if the socket that was closed was not the latest socket to be opened.
Running v 0.12.0

To reproduce this.
1) Start the server below
2) Open two telnet sessions to the server
3) Close the first telnet session
4) Close the second telnet session

``` js
var net = require("net");
var server, socket_id=0;
server = new net.createServer({},function(socket){
    console.log("connected");
    socket.uuid = ++socket_id;
    socket.write("connected");
    socket.on("close",function(has_error){
        console.log("terminated",socket.uuid);
    });
    socket.on("end",function(){
        console.log("disconnected",socket.uuid);
    });
    socket.on("error",function(error){
        console.log("error",socket.uuid,error)
    });
    socket.on("data",function(data){
        console.log("data:",socket.uuid,data)
    });
});
server.listen(23);
```

**Comment by Freyert** [comment] 2015-03-05 20:16
I tried this out on OS X Yosemite v. 10.10.2 with Node v. 0.12.0 and did not encounter the error.

Here is a copy of the program's output:
```
connected
connected
disconnected 1
terminated 1
disconnected 2
terminated 2
```

And here is how I was disconnecting the `telnet` connections:
```
telnet localhost 23
Trying ::1...
Connected to localhost.
Escape character is '^]'.
connected^]
telnet> quit
Connection closed.
```

**Comment by 09silverware** [comment] 2015-03-05 20:54
Windows 7 with v0.12.0
Using PuTTy, closing the connection rather than ending it nicely. Maybe that's what is doing it.
Terminated session 1 first, then session 2.

```
connected
connected
disconnected 2
terminated 2
error 1 { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
terminated 1
```

**Comment by Freyert** [comment] 2015-03-05 21:00
Certainly could be a compatibility issue as well. Check out that StackOverflow article I posted and follow his methodology for debugging the socket. Post what you find!

**Comment by 09silverware** [comment] 2015-03-09 03:12
Tried the same program on Ubuntu 14.04.2 LTS, build from the v0.12.0 source.

Instead of getting the errors I was getting, instead the connection stays open, and doesn't seem to close...
Even after leaving the connection for a long period of time it doesn't seem to close.

Using PuTTY or Windows Telnet and killing the session results in this. If you use a Linux Telnet and close it with "^] quit" or equivalent then it terminates properly, likely due to receiving a fin packet.

Ignoring the data field I get the following.
```
connected
connected
disconnected 2
terminated 2
```

Additionally Longjohn has been throwing errors for me, so have been unable to use it for stack tracing.

**Comment by Freyert** [comment] 2015-03-10 02:51
Great! Looks like the problem is maybe with PuTTY itself. (?) Do you have any experience using a utility like Wireshark? If you're still interested in looking at this I would compare the TCP packets sent in our varying cases which are . . .

* In all settings, Telnet in with two processes. Crash the first telnet session first.
* The Telnet client in question is Windows based.
* Try it in Ubuntu
* Try it in Windows
* Try both environments with the Linux based `telnet`

Collect information on the packets exchanged on closing. This should give us a better idea as to whether or not Node is acting correctly to an incorrect process or if Node is in the wrong.

**Closed** 2023-04-22 17:02 UTC
Labels: net
