### ISSUE TITLE
Wrong os.release()

### ISSUE THREAD

**Issue by maxrimue** [nodejs/node-v0.x-archive#25896] opened 2015-08-25 10:36 UTC
On Windows 10, 'os.release()' gets me '6.3.9600', however, the correct output for Windows 10 should be something with '10.0'. I'm running Node.js v0.12.7 64-bit on a 64-bit Windows 10, and I installed it <i>after</i> I upgraded to Windows 10, if that's important.

**Comment by dnakamura** [comment] 2015-08-25 15:59
Whats the output of ```ver``` command https://en.wikipedia.org/wiki/Ver_(command)

**Comment by maxrimue** [comment] 2015-08-25 16:17
`Microsoft Windows [Version 10.0.10240]`

**Comment by dnakamura** [comment] 2015-08-25 17:47
As it turns this is caused by a change on Microsofts part. Node uses ```GetVersionEx()``` on windows to get the version number.  Apparently the change occurred beginning /w version 8.1. if an application is not manifested for win 8.1, or 10 the function always returns the version num of win 8, otherwise it always returns the lesser of  version number in the manifest, or the actual version number. At the moment I'm looking at a clean way to work around this behavior. It seems the only way to do it is to read the value directly from the registry (which seems kinda hacky)

**Comment by maxrimue** [comment] 2015-08-25 18:09
I'm not that much into C/C++, but I found the following methods:
- Execute `ver` and filter the output to only return the desired numbers
- Query the registry for `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion`, `CurrentVersion` + `CurrentBuild`
- Use `GetVersionEx()`, and if the version equals Windows 8.1, use the booleans of the <a href="https://msdn.microsoft.com/en-us/library/windows/desktop/dn424972(v=vs.85).aspx">Version Helper functions</a>

I'm glad to help, however, I won't be able to provide actual code.

**Comment by joaocgreis** [comment] 2015-08-26 03:13
This seems related: https://github.com/nodejs/node/pull/2332

**Comment by maxrimue** [comment] 2015-08-26 06:14
Yep, that's the same issue. Seems like it can be solved pretty easily.

**Comment by dnakamura** [comment] 2015-08-26 15:12
@maxrimue 
yeah the first 2 options would work, now I'm considering the which is the most robust/future proof. The version helper functions is not appealing since it would require updating the code every time a new build of windows shows up

**Comment by maxrimue** [comment] 2015-08-27 10:06
@dnakamura Since the `ver` command has been available <a href="https://en.wikipedia.org/wiki/Ver_(command)#Version_list">since Windows 1.0</a>, and still is, I don't see Microsoft removing that command any time soon.

**Comment by dnakamura** [comment] 2015-08-27 14:42
@maxrimue  Yeah, the ver command seems the most appealing

**Comment by joaocgreis** [comment] 2015-09-15 08:47
This will be fixed when https://github.com/nodejs/node/pull/2843 lands.

**Comment by maxrimue** [comment] 2015-09-15 16:59
@joaocgreis Nice!

**Comment by joaocgreis** [comment] 2015-09-16 16:02
Done. Should make the v0.12.8 release!

**Closed by joaocgreis** 2015-09-16 16:02 UTC
Labels: windows
