### ISSUE TITLE
ReferenceError on loopier for loop?

### ISSUE THREAD

**Issue by mogmios** [nodejs/node-v0.x-archive#25601] opened 2015-06-30 15:27 UTC
`node-v0.12.4 --harmony --use-strict`

    x = 0; console.time('test'); for(let i = 0; i<1000;i++){ {const v = i; const w = v + v; x += w;}; } console.timeEnd('test'); console.log(x);

test: 0ms
999000

    x = 0; console.time('test'); for(let i = 0; i<10000;i++){ {const v = i; const w = v + v; x += w;}; } console.timeEnd('test'); console.log(x);

ReferenceError: .for is not defined
    at repl:1:100
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)

**Comment by tunniclm** [comment] 2015-07-03 12:38
I managed to reproduce this with these steps:

    $ node --harmony --use-strict
    > let x=0
    > x = 0; console.time('test'); for(let i = 0; i<10000;i++){ {const v = i; const w = v + v; x += w;}; } console.timeEnd('test'); console.log(x);
    test: 4ms
    99990000
    undefined
    > x = 0; console.time('test'); for(let i = 0; i<10000;i++){ {const v = i; const w = v + v; x += w;}; } console.timeEnd('test'); console.log(x);
    ReferenceError: .for is not defined
        at repl:1:100
        at REPLServer.defaultEval (repl.js:132:27)
        at bound (domain.js:254:14)
        at REPLServer.runBound [as eval] (domain.js:267:12)
        at REPLServer.<anonymous> (repl.js:279:12)
        at REPLServer.emit (events.js:107:17)
        at REPLServer.Interface._onLine (readline.js:214:10)
        at REPLServer.Interface._line (readline.js:553:8)
        at REPLServer.Interface._ttyWrite (readline.js:830:14)
        at ReadStream.onkeypress (readline.js:109:10)
    > x = 0; console.time('test'); for(let i = 0; i<10000;i++){ {const v = i; const w = v + v; x += w;}; } console.timeEnd('test'); console.log(x);
    test: 2ms
    99990000
    undefined
    > x = 0; console.time('test'); for(let i = 0; i<10000;i++){ {const v = i; const w = v + v; x += w;}; } console.timeEnd('test'); console.log(x);
    ReferenceError: .for is not defined
        at repl:1:100
        at REPLServer.defaultEval (repl.js:132:27)
        at bound (domain.js:254:14)
        at REPLServer.runBound [as eval] (domain.js:267:12)
        at REPLServer.<anonymous> (repl.js:279:12)
        at REPLServer.emit (events.js:107:17)
        at REPLServer.Interface._onLine (readline.js:214:10)
        at REPLServer.Interface._line (readline.js:553:8)
        at REPLServer.Interface._ttyWrite (readline.js:830:14)
        at ReadStream.onkeypress (readline.js:109:10)

It repeats in a cycle between working and failing.

It does not fail if `x` is declared with `var x` instead of `let x=0`.

It also fails with the loop from `i=0; i<1000`, but only every 6 times it is executed.

**Comment by tunniclm** [comment] 2015-07-03 12:46
Note, I skipped over this detail in my first comment---the code snippet in the original post doesn't reproduce the error for me, since it doesn't declare `x`:
    $ node --harmony --use-strict
    > x = 0; console.time('test'); for(let i = 0; i<20000;i++){ {const v = i; const w = v + v; x += w;}; } console.timeEnd('test'); console.log(x);
    ReferenceError: x is not defined
        at repl:1:3
        at REPLServer.defaultEval (repl.js:132:27)
        at bound (domain.js:254:14)
        at REPLServer.runBound [as eval] (domain.js:267:12)
        at REPLServer.<anonymous> (repl.js:279:12)
        at REPLServer.emit (events.js:107:17)
        at REPLServer.Interface._onLine (readline.js:214:10)
        at REPLServer.Interface._line (readline.js:553:8)
        at REPLServer.Interface._ttyWrite (readline.js:830:14)
        at ReadStream.onkeypress (readline.js:109:10)

**Comment by cjihrig** [comment] 2015-07-03 14:16
@tunniclm is this reproducible on io.js?

**Comment by tunniclm** [comment] 2015-07-03 15:12
@cjihrig I'm not sure, I haven't tried it yet. I did my recreates above with Node.js v0.12.4 and I've just recreated it on Node.js master @ 4ffbce4 (v0.13.0-pre).

**Comment by tunniclm** [comment] 2015-07-03 17:11
@cjihrig Just tested on iojs master @ 9cd44bb2b683446531306bbcff8739fc3526d02c (v2.3.3-pre) and the problem does not occur.

**Comment by cjihrig** [comment] 2015-07-03 23:39
@tunniclm thanks!

Given that this is not present in io.js, is low priority, and depends on the `--harmony` and `--use-strict` flags, I propose closing this.

**Comment by tunniclm** [comment] 2015-10-13 12:10
Closing this issue as proposed. Please feel free to add further comments if you feel more discussion is required.

**Closed by tunniclm** 2015-10-13 12:10 UTC
Labels: S-confirmed-bug
