### ISSUE TITLE
'Hang' after timeout on https request

### ISSUE THREAD

**Issue by alexwhitman** [nodejs/node-v0.x-archive#6928] opened 2014-01-21 22:19 UTC
I've got an application which tests whether a server responds to http and https requests to check if certain IP restrictions have been correctly put in place.  The code works fine unless the server is down.  The following code is similar to the real code and exhibits the same issue.

``` javascript
var http  = require('http');
var https = require('https');

var options = {
        host: 'host',
        port: 80
};

var protocol = http;
if (process.argv[2] && process.argv[2] === 'https') {
        protocol = https;
        options.port = 443;
}

var request = protocol.request(options, function(response) {
        // if we get a response we've connected
        response.destroy();
});

request.on('error', function(error) {
        var now = new Date();
        console.log(now.toISOString());
        console.log(error);
});

request.setTimeout(2000, function() {
        request.destroy();
        var now = new Date();
        console.log(now.toISOString());
        console.log('timeout');
});
```

The output of running the above for http and https is:

```
// HTTP mode
$ node fail.js
2014-01-21T21:36:57.865Z
timeout
2014-01-21T21:36:57.871Z
{ [Error: socket hang up] code: 'ECONNRESET' }

// HTTPS mode
$ node fail.js https
2014-01-21T21:37:02.362Z
timeout
2014-01-21T21:37:02.366Z
{ [Error: socket hang up] code: 'ECONNRESET' }
2014-01-21T21:39:07.629Z
{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
```

Notice how the http mode times out and ends but the https mode times out and then waits for 2 minutes before ending.

`curl` doesn't show have the same issue:

```
$ curl http://host -vvv --connect-timeout 2
* Rebuilt URL to: http://host/
* Adding handle: conn: 0x2598b30
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x2598b30) send_pipe: 1, recv_pipe: 0
* About to connect() to host port 80 (#0)
*   Trying IP...
* Connection timed out after 2001 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 2001 milliseconds

$ curl https://host -vvv --connect-timeout 2
* Rebuilt URL to: https://host/
* Adding handle: conn: 0x237eb30
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x237eb30) send_pipe: 1, recv_pipe: 0
* About to connect() to host port 443 (#0)
*   Trying IP...
* Connection timed out after 2001 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 2001 milliseconds
```

Not sure if this is a bug or me doing something incorrectly but the difference seems odd.  Running 0.10.24 on Ubuntu 13.10 64bit.

**Comment by jasnell** [comment] 2015-05-28 22:20
@trevnorris ... were you ever able to get to this? :-)

**Comment by trevnorris** [comment] 2015-06-01 21:59
nope. sorry.

**Comment by akloeber** [comment] 2016-12-21 20:35
I just retested against node v4.4.1 and I'm not able to reproduce this error. It was definitely an issue back in v0.10 as I still had the workaround in place that @OneOfOne mentioned.

**Comment by MylesBorins** [comment] 2016-12-21 20:36
@akloeber is there a reason why you were testing on v4.4.1 and not v4.7.0?

Either way if you are saying this is not longer an issue I am going to close this, thanks for letting us know.

**Closed by MylesBorins** 2016-12-21 20:36 UTC
Labels: https

**Comment by akloeber** [comment] 2016-12-21 21:06
@TheAlphaNerd there is no specific reason other than v4.4.1 being our current production version.

**Comment by MylesBorins** [comment] 2016-12-21 21:07
@akloeber I highly advise bumping that up since there have been quite a few security releases since then.

**Comment by akloeber** [comment] 2016-12-21 21:24
@TheAlphaNerd I can also confirm that the error is fixed in v4.7.0. We are going to upgrade our node versions as soon as possible.

**Comment by alexwhitman** [comment] 2016-12-22 08:53
It wasn't an issue in `master` at the time of reporting so it's no surprise that the problem doesn't exist in versions 3 years later.

**Comment by akloeber** [comment] 2016-12-22 11:08
@alexwhitman I have no idea how branch and release management for Node.js works but for sure the official release v0.10.40 that we had in production back then showed the described behavior.

This can still be reproduced with the following script:
```js
var http  = require('http');
var https = require('https');

var options = {
  host: '4.2.2.2',
  port: 80
};

var protocol = http;
if (process.argv[2] && process.argv[2] === 'https') {
  protocol = https;
  options.port = 443;
}

console.log(new Date().toISOString(), 'request');
var request = protocol.request(options, function(response) {
  response.destroy();
});

request.on('error', function(error) {
  console.log(new Date().toISOString(), 'error', error);
});

request.setTimeout(2000, function() {
  request.destroy();
  console.log(new Date().toISOString(), 'timeout');
});
```

```bash
$ nvm use 0.10.40
Now using node v0.10.40 (npm v2.14.1)
$ node fail.js
2016-12-22T10:04:05.071Z request
2016-12-22T10:04:07.079Z timeout
2016-12-22T10:04:07.080Z error { [Error: socket hang up] code: 'ECONNRESET' }
$ node fail.js https
2016-12-22T10:04:10.218Z request
2016-12-22T10:04:12.238Z timeout
2016-12-22T10:04:12.238Z error { [Error: socket hang up] code: 'ECONNRESET' }
2016-12-22T10:05:34.708Z error { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
```

**Comment by MylesBorins** [comment] 2016-12-22 14:59
0.10 is end of life and no longer receiving support or updates from the project

**Comment by akloeber** [comment] 2016-12-22 19:11
@TheAlphaNerd Yes, I know that 0.10 is EOL and so is 0.12. As I said: we are currently on node 4.x and moving towards 6.x.

I was referring to @alexwhitman's comment that it 

> "... wasn't an issue in master at the time of reporting so it's no surprise that the problem doesn't exist in versions 3 years later."

In fact around the time when this issue was reported, 0.10.x was current, we ran into this problem with v0.10.40 and needed to put a workaround in place to mitigate the described behavior. It might be true that the issue was never present on branch `master` but somehow it made it into several 0.10.x releases (see my comment to reproduce with v0.10.40).
So from my point of view it was not self-evident that this issue can not be present in recent node versions (even 3 years later), which was also reinforced by the fact that this issue had still been open until yesterday.
