### ISSUE TITLE
timers.js assertionError

### ISSUE THREAD

**Issue by jdwissler** [nodejs/node-v0.x-archive#8383] opened 2014-09-16 20:27 UTC
```
assert.js:98
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at Timer.listOnTimeout (timers.js:156:3)
```

I'm not sure what is causing this, other than it being setTimeout. 

It looks like it corresponds to this line of code on my version of nodejs:

```
 assert(L.isEmpty(list));
```

I am using nodejs v0.11.13 on Ubuntu 12.04.

This also happends with node v0.10.31:

```
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at Timer.listOnTimeout [as ontimeout] (timers.js:133:3)

```

**Comment by jasnell** [comment] 2015-06-03 19:59
@jdwissler ... is this still an issue for you? If it is, any luck providing a test case we can use to reliably reproduce the problem?

**Comment by poilss** [comment] 2015-07-04 13:50
I have no idea if this is OP's cause, but I was quite amazed when I traced my cause to this:

    Object.defineProperty(Object.prototype, 'isEmpty', {value: function() {
      for (var prop in this)
        if (this.hasOwnProperty(prop))
          return false;
      return true;
    }});
    
    setTimeout(function(){});

Are we forbidden to add anything to such prototypes in node.js? (there's even no isEmpty method on Object) If yes, that's sad. If no, I suspect there's a whole minefield of bugs like this...

**Comment by cjihrig** [comment] 2015-07-06 16:56
@poilss adding things to Object prototype is a controversial topic, but you should be able to do it. I ran your code in io.js and had no problem.

**Comment by Fishrock123** [comment] 2016-12-22 15:45
Various related bugs have been fixed in the time since and so finding the reported problem without source code is impossible.

Our tests are better now too, I doubt the assertions are necessary anymore.

**Closed by Fishrock123** 2016-12-22 15:45 UTC
Labels: timer
