### ISSUE TITLE
fs.rename callback called before finish

### ISSUE THREAD

**Issue by jaderfabiano** [nodejs/node-v0.x-archive#7770] opened 2014-06-11 18:17 UTC
Hi.
I am using this function fs.rename and sometimes the callback is being called before terminate.
What is this happening?

Thanks!

**Comment by jamesjenner** [comment] 2015-02-27 05:38
I suspect I have a similar problem. Rename still holds a lock (or the action is not complete, not sure which) when the callback is called on fs.rename(). I'll write a test case to confirm what the problem is.

**Comment by jamesjenner** [comment] 2015-03-01 23:37
I've created a complex test case where I perform the following:

1. open source and target file
2. read source into buffer
3. process input on a per line bases ('/n') 
4. write each line to target file
5. close both files
6. delete source file
7 rename target to source

Works with no problems. The above is don with sync versions of the various operations with the exception of the rename. 

My problem was due to using the async rename. Only caused a problem with mocha as various tests were using the same files.

Code used is as follows:

    var fs = require ('fs');

    var filename = "test.txt";

    // open in
    var inFd = openFile(filename);

    if(inFd === null) {
      console.error("error opening file: " + filename);
      return;
    }


    // open out
    var outFd = openFile(filename + ".tmp", 'w');

    if(outFd === null) {
      console.error("error opening file: " + filename);
      return;
    }

    var currentLineNumber = 0;
    var buffer = new Buffer(1024);
    var bytesRead = 0;
    var line = '';
    var idxStart = 0;
    var idx = 0;
    var leftOver;
    var wBuffer;

    // loop through the entire file
    while ((bytesRead = fs.readSync(inFd, buffer, 0, 512, null)) !== 0) {
      // convert buffer to string and append to left over
      leftOver += buffer.toString('utf8', 0, bytesRead);

      idxStart = 0;
      // loop through the buffer for each line terminator
      while ((idx = leftOver.indexOf("\n", idxStart)) !== -1) {
        // increment the index so that the \n is kept

        // set the line based on the current line terminator
        line = leftOver.substring(idxStart, idx + 1);

        currentLineNumber++;

        // write the line
        try {
          line = currentLineNumber + " " + line;
          console.log("writing: " + line);
          var wBuffer = new Buffer(line);
          // note that new Buffer uses utf8 unless otherwise specified, it's possible that ascii should be used instead (nulls are converted to 0x20)
          bytesWritten = fs.writeSync(outFd, wBuffer, 0, line.length);
        } catch (e) {
          console.error("Error writing " + filename + ".tmp" + ": " + e);
        }


        // incrememnt index
        idxStart = idx + 1;
      }

      // set leftOver to what wasn't processed
      leftOver = leftOver.substring(idxStart);
    }

    // close the files
    closeFile(inFd, filename);
    closeFile(outFd, filename + ".tmp");

    moveFile(filename + ".tmp", filename);

    function moveFile(sourceFilename, targetFilename) {

      fs.unlink(targetFilename, function (e) {
        if(e) {
          console.error("Error removing " + targetFilename + ": " + e);
        } else {
          fs.rename(sourceFilename, targetFilename, function(e) {
            if(e) {
              console.error("Error renaming " + sourceFilename + " to " + targetFilename + ": " + e);
            }
          });
        }
      });  
    }

    function openFile(filename, flags) {
      var fd = null;

      flags = ((flags !== null && flags !== undefined) ? flags : 'r');

      try {
        fd = fs.openSync(filename, flags);
      } catch (e) {
        console.error("Error opening " + filename + ": " + e);
      }

      return fd;
    }

    function closeFile(fd, filename) {
      try {
        fs.closeSync(fd);
      } catch (e) {
        console.error("Error closing " + filename + " : " + e);
      }
    }

The contents of `test.txt` was a lorum ipsum generated text for 80 lines, total size 16Kb. To generate text just use lipsum.com with 100 as the option for the generator.

**Comment by jasnell** [comment] 2015-03-03 23:29
On Mac OSX 10.10, using v0.12.0, just ran a very quick test case:

1. Created test.txt with a few hundred lines of lorem boilerplate
2. Ran the following:

```javascript
var fs = require('fs');

fs.rename('test.txt', 'test.foo', function(err) {
  console.log(fs.statSync('test.foo'));
  console.log('....');
  console.log(fs.statSync('test.txt'));
});
```
Every run occurs as expected.

**Closed** 2023-04-22 17:02 UTC
Labels: fs
