### ISSUE TITLE
While I build Node.js 0.12.0,it shows '../src/node.cc:3000:7:error:'SSL2_ENABLE' was not decleared in this scope'

### ISSUE THREAD

**Issue by visoft-viscrop** [nodejs/node-v0.x-archive#25827] opened 2015-08-09 03:00 UTC
root@localhost:~/node-v0.12.0# make -C out BUILDTYPE=Release V=1
make[1]: Entering directory `/root/node-v0.12.0/out'
  g++ '-DNODE_WANT_INTERNALS=1' '-DARCH="arm"' '-DPLATFORM="linux"' '-DNODE_TAG=""' '-DNODE_V8_OPTIONS=""' '-DHAVE_OPENSSL=0' '-D__POSIX__' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_POSIX_C_SOURCE=200112' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/root/node-v0.12.0/out/Release/obj/gen -I../deps/debugger-agent/include -I../deps/v8/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -pthread -Wall -Wextra -Wno-unused-parameter -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF /root/node-v0.12.0/out/Release/.deps//root/node-v0.12.0/out/Release/obj.target/node/src/node.o.d.raw  -c -o /root/node-v0.12.0/out/Release/obj.target/node/src/node.o ../src/node.cc
../src/node.cc: In function 'void node::ParseArgs(int*, const char**, int*, const char***, int*, const char***)':
../src/node.cc:3000:7: error: 'SSL2_ENABLE' was not declared in this scope

**Comment by visoft-viscrop** [comment] 2015-08-09 03:03
Over is make

**Comment by brendanashworth** [comment] 2015-10-13 00:03
This seems like it is a duplicate of https://github.com/nodejs/node-v0.x-archive/issues/8645, closing.

**Closed by brendanashworth** 2015-10-13 00:03 UTC
