### ISSUE TITLE
Don't run close events in process.nextTick()

### ISSUE THREAD

**Issue by trevnorris** [nodejs/node-v0.x-archive#7996] opened 2014-07-24 23:53 UTC
Example:

``` javascript
var net = require('net');

setImmediate(function() {
  process._rawDebug('setImmediate');
});


(function createServer() {
  net.createServer(function() { }).listen(8000, function() {
    this.close();
    createServer();
  });
}());
```

The above doesn't allow the `setImmediate()` to ever run since the `close` callbacks are called in `process.nextTick()`. Instead it ends up in an endless loop and causes massive memory usage until the program crashes.

The simplest solution would be to call the `close` callbacks in a `setImmediate()`, but the "correct" solution would be to have them called in the `uv__run_closing_handles()` phase of the event loop.

Assigning to myself, but if any other contributors have ideas please chime in.

**Comment by brendanashworth** [comment] 2015-10-01 05:04
@trevnorris at first glance this seems to be on-par with expected behavior to me. Do you still want to pursue this and open a new issue @ nodejs/node or should we just close this?

**Comment by trevnorris** [comment] 2015-10-01 05:23
IIRC it shows an inconsistency. If a hostname is passed to listen() then internally it will do a lookup and force a cycle of the event loop. Allowing the setImmediate to fire. I think a fox for this should be explored, though also low priority.

**Closed** 2023-04-22 17:02 UTC
