### ISSUE TITLE
Resource leak detected

### ISSUE THREAD

**Issue by JacksonTian** [nodejs/node-v0.x-archive#25322] opened 2015-05-14 13:37 UTC
```
#
# Fatal error in ../deps/v8/src/handles.h, line 48
# CHECK(location_ != NULL) failed
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::String::NewExternal(v8::Isolate*, v8::String::ExternalAsciiStringResource*)
 3: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding)
 4: void node::Buffer::StringSlice<(node::encoding)2>(v8::FunctionCallbackInfo<v8::Value> const&)
 5: ??
uncaughtException:AssertionError: Resource leak detected. 
```

The issue caused by operate Buffer, woker get fatal error, and master get AssertionError also. Is the assert necessary in cluster when use cluster-worker mode?

**Comment by dnakamura** [comment] 2015-05-14 19:42
What version of nod are you running? Also, can you give a small code example to reproduce?

**Comment by mhdawson** [comment] 2015-06-11 21:02
@JacksonTian  any chance you can provide the info requested by @dnakamura

**Comment by JacksonTian** [comment] 2015-06-12 01:54
in worker.js:

```
new Buffer(new Date().getTime());
```
it make a big buffer and crash, then the master.js will get the error.

master.js cluster fork the work.js

**Comment by brendanashworth** [comment] 2015-09-29 06:33
`new Date().getTime()` turns out to be about a terabyte of a single buffer (~`1443508316617` bytes), which is way to big for your system to handle, most probably. I'll close this as a non-issue, please reopen if you don't think so.

**Closed by brendanashworth** 2015-09-29 06:33 UTC

**Comment by ChALkeR** [comment] 2015-09-29 06:41
This is fixed, btw:

``` javascript
> new Buffer(new Date().getTime());
RangeError: Invalid typed array length
    at new Uint8Array (native)
    at allocate (buffer.js:89:17)
    at new Buffer (buffer.js:48:12)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:392:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
```

It does not crash, but throws a `RangeError`.
