### ISSUE TITLE
Debugger: vm.runInDebugContext change behavior in 0.11.16

### ISSUE THREAD

**Issue by 3y3** [nodejs/node-v0.x-archive#9156] opened 2015-02-06 21:40 UTC
``` js
var vm = require('vm');
var assert = require('assert');

var proto = vm.runInDebugContext('DebugCommandProcessor.prototype');
proto.option_ = true;
assert(proto.option_ === true);
proto = vm.runInDebugContext('DebugCommandProcessor.prototype');
assert(proto.option_ === true);
proto = vm.runInDebugContext('DebugCommandProcessor.prototype.option_ = true; DebugCommandProcessor.prototype');
assert(proto.option_ === true);
```

This test passes in 0.11.14 and fails in 0.11.16.
I think this is relative to 947408b025c3429b6c80901749e7866e04ec3fe0
@indutny , please confirm this.

Previous behavior is very important for node-inspector. This is my current way to extend v8 debugger protocol. If new behavior is correct, can you propose any way to extend debugger protocol after 0.11.16 and in io.js

**Comment by indutny** [comment] 2015-02-06 21:53
Looking

**Comment by indutny** [comment] 2015-02-06 22:22
This is not caused by 947408b for sure, happens on a2a3fd4 too.

**Comment by indutny** [comment] 2015-02-06 22:38
I think it was broken during the merge 7ca5af8

**Comment by indutny** [comment] 2015-02-06 22:41
Hm... may be not.

**Comment by indutny** [comment] 2015-02-06 22:51
Btw, doesn't seem to be working on v0.11.14 for me.

**Comment by indutny** [comment] 2015-02-06 22:54
And on v0.11.15 too.

**Comment by indutny** [comment] 2015-02-06 22:55
Same on v0.11.16 ... @3y3 am I missing something? This feature was introduced in v0.11.14 and your test case does not appear to be working with any versions after (and including) it.

**Comment by 3y3** [comment] 2015-02-06 22:56
Hm... Win x64 works on 0.11.14 for me (downloaded from site).

**Comment by indutny** [comment] 2015-02-06 22:58
@tjfontaine @misterdjules can we confirm this on windows? (I don't have any machines at hand)

**Comment by 3y3** [comment] 2015-02-06 23:05
I also backported this feature to previous versions in `v8-debug` project (small core of node-inspector) [link](https://github.com/node-inspector/v8-debug/blob/master/src/debug.cc#L36-L48) and it works fine excluding to 0.11.15+

**Comment by indutny** [comment] 2015-02-06 23:07
@3y3 it is failing on:

```
var proto = vm.runInDebugContext('DebugCommandProcessor.prototype');
proto.option_ = true;
```

for me

**Comment by indutny** [comment] 2015-02-06 23:08
```
~/Code/joyent/node $ ./node -p "process.version"
v0.11.16
~/Code/joyent/node $ cat 1.js
var vm = require('vm');
var assert = require('assert');

var proto = vm.runInDebugContext('DebugCommandProcessor.prototype');
assert(proto.option_ === true);
proto = vm.runInDebugContext('DebugCommandProcessor.prototype');
assert(proto.option_ === true);
proto = vm.runInDebugContext('DebugCommandProcessor.prototype.option_ = true; DebugCommandProcessor.prototype');
assert(proto.option_ === true);
~/Code/joyent/node $ ./node 1

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at Object.<anonymous> (/Users/indutny/Code/joyent/node/1.js:5:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by indutny** [comment] 2015-02-06 23:08
Gosh. I got this line removed somehow, sorry about this! :)

**Comment by 3y3** [comment] 2015-02-06 23:24
### Success
```ps
D:\3y3\GIT\v8-debug [master +3 ~5 -0 !]> node -p "process.version + ' ' + process.arch"
v0.11.14 ia32
D:\3y3\GIT\v8-debug [master +3 ~5 -0 !]> cat test.js
var vm = require('vm');
var assert = require('assert');

var proto = vm.runInDebugContext('DebugCommandProcessor.prototype');
proto.option_ = true;
assert(proto.option_ === true);
proto = vm.runInDebugContext('DebugCommandProcessor.prototype');
assert(proto.option_ === true);
proto = vm.runInDebugContext('DebugCommandProcessor.prototype.option_ = true; DebugCommandProcessor.prototype');
assert(proto.option_ === true);
D:\3y3\GIT\v8-debug [master +3 ~5 -0 !]> node test
D:\3y3\GIT\v8-debug [master +3 ~5 -0 !]>
```

### Failure
```ps
D:\3y3\GIT\v8-debug [master +3 ~5 -0 !]> node -p "process.version + ' ' + process.arch"
v0.11.15 ia32
D:\3y3\GIT\v8-debug [master +3 ~5 -0 !]> cat test.js
var vm = require('vm');
var assert = require('assert');

var proto = vm.runInDebugContext('DebugCommandProcessor.prototype');
proto.option_ = true;
assert(proto.option_ === true);
proto = vm.runInDebugContext('DebugCommandProcessor.prototype');
assert(proto.option_ === true);
proto = vm.runInDebugContext('DebugCommandProcessor.prototype.option_ = true; DebugCommandProcessor.prototype');
assert(proto.option_ === true);
D:\3y3\GIT\v8-debug [master +3 ~5 -0 !]> node test

assert.js:99
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at Object.<anonymous> (D:\3y3\GIT\v8-debug\test.js:8:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
D:\3y3\GIT\v8-debug [master +3 ~5 -0 !]>
```

Not relative to error but I'm sorry for 
> Hm... Win x64 works

I don't know why I use x32 arch in 0.11.15, but in 0.11.14 it was important for `node-pre-gyp`...

**Comment by indutny** [comment] 2015-02-06 23:29
Ok, the offending commit seems to be 9116b240c924d37627313416b7ee038d0580afbc

**Comment by indutny** [comment] 2015-02-06 23:49
Hah, actually 7a0cfe9 as you initially said :)

This appears to be fixing the problem:

```diff
diff --git a/src/node_contextify.cc b/src/node_contextify.cc
index 6985a33..d4e284d 100644
--- a/src/node_contextify.cc
+++ b/src/node_contextify.cc
@@ -236,6 +236,10 @@ class ContextifyContext {
     Local<String> script_source(args[0]->ToString(args.GetIsolate()));
     if (script_source.IsEmpty())
       return;  // Exception pending.
+    Environment* env = Environment::GetCurrent(args);
+    Local<Context> ctx = Debug::GetDebugContext();
+    if (!ctx.IsEmpty())
+      ctx->SetSecurityToken(env->context()->GetSecurityToken());
     Context::Scope context_scope(Debug::GetDebugContext());
     Local<Script> script = Script::Compile(script_source);
     if (script.IsEmpty())
```

@3y3 do you have resources to verify it?

**Comment by 3y3** [comment] 2015-02-06 23:53
I'll try to rebuild my 0.11.16 now

**Comment by indutny** [comment] 2015-02-06 23:57
Just opened PR: https://github.com/joyent/node/pull/9157

**Comment by indutny** [comment] 2015-02-07 01:12
@3y3 unfortunately, it does not fix the issue. Going to look into it tomorrow.

**Comment by indutny** [comment] 2015-02-08 00:00
Most likely `wontfix` as per https://code.google.com/p/v8/issues/detail?id=3876&thanks=3876&ts=1423353590 .

**Comment by 3y3** [comment] 2015-02-08 13:16
Wow! It's a bad news. I subscribed on v8 issue.
So if it will be `wontfix`, I'll think about pr for `debugger_agent`. It's a last place where I can inject debugger extensions dynamically.
And now I need to make console tracing and profiling more optionally for node-inspector, because this features based on dinamic injection.

About new `debugger_agent` - is this a main gateway for @bmeck work on `Using webkit debugger protocol`?

**Comment by indutny** [comment] 2015-02-08 13:23
@3y3 I have no idea :) How are you using this `DebugCommandProcessor` anyway?

**Comment by 3y3** [comment] 2015-02-08 13:59
I do next
```js
DebugCommandProcessor.prototype.processDebugRequest = function WRAPPED_BY_NODE_INSPECTOR(request) {
    return this.extendedProcessDebugJSONRequest_(request)
      || this.processDebugJSONRequest(request);
  };
DebugCommandProcessor.prototype.extendedProcessDebugJSONRequest_ = function(request) {
  // if request exists in extendedProcessDebugJSONRequestHandles_ 
  // then process it
  // else return false
}
DebugCommandProcessor.prototype.extendedProcessDebugJSONRequestHandles_ = {};
```
This way a hack [this line of code](https://github.com/joyent/node/blob/master/deps/v8/src/debug.cc#L2899-L2901). **So in current time this line is unhackable =(**

I provide small api to write in `extendedProcessDebugJSONRequestHandles_` and call commands. 

From `node-inspector` source:
```js
debug.registerCommand('Profiler.stop', function(request, response) {
    var profile = profiler.stopProfiling();
    profilingEnabled = false;
    response.body = {header: profile.getHeader()};

    debug.sendCommand(
      'Profiler.addProfileHeader',
      response.body
    );

    debug.sendCommand(
      'Profiler.setRecordingProfile',
      {isProfiling: false}
    );
  });
```

So `debug.sendCommand` is a wrapped `v8::Debug::SendCommand`.

**Comment by 3y3** [comment] 2015-02-09 20:31
Ok =) As temporary fix I use next strategy:
```
v8::Debug::Call(function(exec_state) {

});

**Comment by 3y3** [comment] 2015-02-09 20:34
@indutny , where I need to open isues for `debugger-agent`?

For example current iisue is `Unhandled error event`

**Comment by indutny** [comment] 2015-02-09 20:37
@3y3 you could do it in node.js or io.js repo, depends on what works for you best.

**Comment by 3y3** [comment] 2015-02-14 22:48
@indutny , is it possible to share `_debugAPI` with main thread `process` object?

It will be nice to use `_debugAPI.sendCommand` as entry point to extensible debugger protocol.
So I'll be glad to use it by way described below:
```js
process._debugAPI.sendCommand = (function(originalSendCommand) {
  return function(command) {
    // do here something
   originalSendCommand();
  }
}(process._debugAPI.sendCommand))
```

v8 issue was accepted, but I don't know that it means for us (is this "ok, we well fix it in future" or "ok, we see it and we will think to fix it or not" ?)

**Comment by indutny** [comment] 2015-03-10 01:38
This is what `v8` team has replied, just in case:

```
When the debugger becomes active, the debug context is loaded and kept via handle. Once the debugger becomes inactive, the handle is cleared. When the debugger becomes active again, a new debug context is loaded.

You can keep the debug context alive by:
- Keep it in a persistent handle so that you can use it. However, internal debugger functionality will still run in fresh debug contexts when it needs to execute something in a debug context, and the debugger has not been active.
- Or keep the debugger active by registering a debug event listener or message listener.
```

**Comment by 3y3** [comment] 2015-03-10 12:21
Oh, yes! I'm already [implement](https://github.com/node-inspector/v8-debug/blob/master/v8-debug.js#L103-L123) noop `debug event listener` in `v8-debug` module. This solution works fine.

`persistent handle` doesn't work for me. Maybe I cook it wrong.

I'm not sure that `debug event listener` needs to be a part of `node`.
Maybe reasonable to redefine `runInDebugContext` to private `_runInDebugContext`, like `process._debugProcess`? This will block common users from using this suspicious behavior.

**Closed** 2023-04-22 17:00 UTC
Labels: debugger
