### ISSUE TITLE
Assertion failed: (0), function uv_err_name, file ../deps/uv/src/uv-common.c, line 74.

### ISSUE THREAD

**Issue by Ognian** [nodejs/node-v0.x-archive#8490] opened 2014-10-02 10:46 UTC
This happens both on 0.11.3 and 0.11.4 and leads to the immediate termination of the worker.
I turned on net debugging and this is the log:
![bildschirmfoto 2014-10-01 um 17 23 52](https://cloud.githubusercontent.com/assets/1231174/4489654/41c61526-4a1e-11e4-9a3c-0931398566bc.png)

The problem happens when trying to connect to a host __ip__ which network cable was pulled out (when the __ip__ is reachable everything works):
```
NET: connect: find host __ip__
NET: connect: dns options
Assertion failed: (0), function uv_err_name, file ../deps/uv/src/uv-common.c, line 74.
```
```netstat -a``` doesn't show any connections to __ip__ (which is OK)
```arp -a``` has also no entry for the __ip__ (which is OK too)
I'm on OS X 10.9.5

Any Ideas?
Thanks a lot
Ognian

**Comment by kdemarest** [comment] 2015-05-04 00:59
Got this in node v0.12.0:
```
Assertion failed: (0), function uv_err_name, file ../deps/uv/src/uv-common.c, line 75.
Abort trap: 6
```
I have not reproduced it. It was during a long debug session on OSX 10.10.1, and as I was restarting my server (was opening both http and ws) this began to occur 100% repeatably.

I only mention it because #1512 appears closed, yet I got this error.

**Comment by spemmons** [comment] 2015-05-08 21:08
I've just got this as well. It's intermittent. I am scanning local IP addresses and have an "error" event handler on my Socket objects -- not sure why this error isn't trapped. I expect errors given that I'm scanning, but I expected my handler to trap them...

**Comment by saghul** [comment] 2015-05-08 21:44
@spemmons this is a an assert in C, it doesn't propagate to JS. You'll need to use strace or dtruss to know the cause. See the comments above.

**Comment by spemmons** [comment] 2015-05-08 22:03
@saghul, makes sense -- kind of a node newbie -- sorry.

A few more details:

The error occurs for me on OSX 10.10.3 using node v0.12.0 as the previous person.

My target platform is an embedded Linux using v0.10.0 which does not exhibit the problem.

**Comment by geoguide** [comment] 2015-08-11 20:54
I am also suddenly getting this error, I would love to know what's the deal since it causes requests to just fail randomly.

`Assertion failed: (0), function uv_err_name, file ../deps/uv/src/uv-common.c, line 75.`

**Comment by dcolens** [comment] 2015-08-24 12:37
node: ../deps/uv/src/uv-common.c:143: uv_err_name: Assertion `0' failed. on 
- node v0.12.7
- ubuntu 14.04

no repro found

**Comment by yura415** [comment] 2015-09-27 15:29
```
Assertion failed: (0), function uv_err_name, file ../deps/uv/src/uv-common.c, line 143.
Abort trap: 6
```

iojs v3.2.0 / OSX 10.10

**Comment by saghul** [comment] 2015-09-27 19:46
Please folks, read previous comments on this issue before posting the exact same thing again. It's just not possible to guess what error triggered the assert without a coredump or strace output.

At any rate, this issue was fixed in https://github.com/libuv/libuv/commit/96fc77d5d998d7a70c4a1c705900432a7a4f828d, which is past of iojs >= 3.3.0 / node 4.

@indutny (or anyone), can this be closed?

**Closed** 2015-09-28 08:37 UTC
Labels: net
