### ISSUE TITLE
Loosing data when downloading via https with connection:close header

### ISSUE THREAD

**Issue by matthiasg** [nodejs/node-v0.x-archive#8488] opened 2014-10-02 07:42 UTC
I am experiencing an issue that might be related to https://github.com/joyent/node/issues/8299. I have been hunting this down all morning and got the following so far:

When downloading a file via https i seem to miss a few bytes at the very end in a large number of cases when 'Connection':'Close' header is present in the Client Request.

e.g. This always works:

```
out = fs.createWriteStream('out.dat')
https.get('https://url').pipe(out)
out.once('finish',verifySizeOfDownload); // always works
```

This fails often:
```
  out = fs.createWriteStream('out.dat')

  var options = require('url').parse('https://myurl.com/test.dat');
  options.headers = {
    Accept: '*/*',
    Connection: 'close'   // when leaving this line out it works all the time. equivalent to passing a string instead of an options object.
  };

  https.get(options, function(res){
    res.pipe(out);
  })

 out.once('finish',verifySizeOfDownload); // often fails
```
The Server is a minimal 'express' server sending a static file back on a get request using `res.sendfile`.

PS:
it didnt help a lot of course that streams have the events 'close','end','finish' and some streams throw different e.g 'end' events ... but not others. But reading the source code and the docs, i would assume binding to finish it is correct to assume the file to be fully flushed. When counting the bytes as they are passed to the filestream using a transform stream, i also get a consistent `_flush` too early for the failing cases.  (Also see https://github.com/joyent/node/pull/8209)

Because of that i looked higher in the stream stack and since a standard call always worked,
but adding a header `'Connection':'close'` does not in a large number of cases (Windows and SmartOS). I would rather assume something is wrong with how the http/s requests handle the close and flush down stream.

Thoughts ?

**Comment by argon** [comment] 2015-06-13 15:11
@matthiasg I discovered #8299 and I want to try to come up with a fix but a reproducible test case is difficult. Would you still be able to supply me with a reproducible test case for this problem so I can check whether it's the same underlying problem?

**Comment by matthiasg** [comment] 2015-06-13 16:33
Unsure .. But I can test again ... Which version spoiled I test against (node / iojs)

-----Original Message-----

**Comment by misterdjules** [comment] 2015-09-25 21:45
Possible duplicate of https://github.com/nodejs/node/issues/3055.

**Comment by jasnell** [comment] 2016-04-09 05:39
Closing as a duplicate of https://github.com/nodejs/node/issues/3055

**Closed by jasnell** 2016-04-09 05:39 UTC
Labels: http, https, tls
